/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  \verbatim
 *  Copyright (c) 2025 by Vector Informatik GmbH.                                                  All rights reserved.
 *
 *                This software is copyright protected and proprietary to Vector Informatik GmbH.
 *                Vector Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vector Informatik GmbH.
 *  \endverbatim
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -----------------------------------------------------------------------------------------------------------------*/
/** \file  File:  BrsHw_Ports.h
 *      Project:  Vector Basic Runtime System
 *       Module:  BrsHw for platform Renesas RH850
 *
 *  \brief Description:  This header file contains the information for the evalboard specific port settings,
 *                       supported by this Brs implementation.
 *
 *  \attention Please note:
 *    The demo and example programs only show special aspects of the software. With regard to the fact
 *    that these programs are meant for demonstration purposes only, Vector Informatik liability shall be
 *    expressly excluded in cases of ordinary negligence, to the extent admissible by law or statute.
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  REVISION HISTORY
 *  -------------------------------------------------------------------------------------------------------------------
 *  Refer to BrsHw.h.
 *********************************************************************************************************************/

#ifndef _BRSHW_PORTS_H_
#define _BRSHW_PORTS_H_

/*******************************************************************************
 *  Generic PORT definition types
 *******************************************************************************/
typedef enum
{
  BRSHW_PORT_PORTGROUP_0,
  BRSHW_PORT_PORTGROUP_1,
  BRSHW_PORT_PORTGROUP_2,
  BRSHW_PORT_PORTGROUP_3,
  BRSHW_PORT_PORTGROUP_4,
  BRSHW_PORT_PORTGROUP_5,
  BRSHW_PORT_PORTGROUP_6,
  BRSHW_PORT_PORTGROUP_7,
  BRSHW_PORT_PORTGROUP_8,
  BRSHW_PORT_PORTGROUP_9,
  BRSHW_PORT_PORTGROUP_10,
  BRSHW_PORT_PORTGROUP_11,
  BRSHW_PORT_PORTGROUP_12,
  BRSHW_PORT_PORTGROUP_13,
  BRSHW_PORT_PORTGROUP_14,
  BRSHW_PORT_PORTGROUP_15,
  BRSHW_PORT_PORTGROUP_16,
  BRSHW_PORT_PORTGROUP_17,
  BRSHW_PORT_PORTGROUP_18,
  BRSHW_PORT_PORTGROUP_19,
  BRSHW_PORT_PORTGROUP_20,
  BRSHW_PORT_PORTGROUP_21,
  BRSHW_PORT_PORTGROUP_22,
  BRSHW_PORT_PORTGROUP_23,
  BRSHW_PORT_PORTGROUP_24,
  BRSHW_PORT_PORTGROUP_25,
  BRSHW_PORT_PORTGROUP_26,
  BRSHW_PORT_PORTGROUP_27,
  BRSHW_PORT_PORTGROUP_28,
  BRSHW_PORT_PORTGROUP_29,
  BRSHW_PORT_PORTGROUP_30,
  BRSHW_PORT_PORTGROUP_31,
  BRSHW_PORT_PORTGROUP_32,
  BRSHW_PORT_PORTGROUP_33,
  BRSHW_PORT_PORTGROUP_34,
  BRSHW_PORT_PORTGROUP_35,
  BRSHW_PORT_PORTGROUP_36,
  BRSHW_PORT_PORTGROUP_37,
  BRSHW_PORT_PORTGROUP_38,
  BRSHW_PORT_PORTGROUP_39,
  BRSHW_PORT_PORTGROUP_40,
  BRSHW_PORT_PORTGROUP_41,
  BRSHW_PORT_PORTGROUP_42,
  BRSHW_PORT_PORTGROUP_43,
  BRSHW_PORT_PORTGROUP_44,
  BRSHW_PORT_PORTGROUP_45,
  BRSHW_PORT_PORTGROUP_46,
  BRSHW_PORT_PORTGROUP_47
}brsHw_Port_PortGroupType;

typedef enum
{
  BRSHW_PORT_PORTNUMBER_0,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_PORTNUMBER_4,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_PORTNUMBER_8,
  BRSHW_PORT_PORTNUMBER_9,
  BRSHW_PORT_PORTNUMBER_10,
  BRSHW_PORT_PORTNUMBER_11,
  BRSHW_PORT_PORTNUMBER_12,
  BRSHW_PORT_PORTNUMBER_13,
  BRSHW_PORT_PORTNUMBER_14,
  BRSHW_PORT_PORTNUMBER_15,
  BRSHW_PORT_PORTNUMBER_16
}brsHw_Port_PortNumberType;

typedef enum
{
  BRSHW_PORT_ALT_0,
  BRSHW_PORT_ALT_1,
  BRSHW_PORT_ALT_2,
  BRSHW_PORT_ALT_3,
  BRSHW_PORT_ALT_4,
  BRSHW_PORT_ALT_5,
  BRSHW_PORT_ALT_6,
  BRSHW_PORT_ALT_7,
  BRSHW_PORT_ALT_8,
  BRSHW_PORT_ALT_9
}brsHw_Port_AlternativeType;

typedef enum
{
  PORT_PULL_UP_DISABLED,
  PORT_PULL_UP_ENABLED
}brsHw_Port_PullUpOption;

typedef enum
{
  PORT_DRIVE_STRENGTH_CONTROL_DISABLED,
  PORT_DRIVE_STRENGTH_CONTROL_ENABLED
}brsHw_Port_PortDriveStrength;

typedef enum
{
  PORT_OPEN_DRAIN_CONTROL_DISABLED,
  PORT_OPEN_DRAIN_CONTROL_ENABLED
}brsHw_Port_PortOpenDrainControl;

typedef enum
{
  PORT_INPUT_BUFFER_CONTROL_DISABLED,
  PORT_INPUT_BUFFER_CONTROL_ENABLED
}brsHw_Port_InputBufferSelect;

typedef enum
{
  PORT_PROTECTION_COMMAND_DISABLED,
  PORT_PROTECTION_COMMAND_ENABLED
}brsHw_Port_PortProtectionCommand;

typedef enum
{
  PORT_PROTECTION_STATUS_DISABLED,
  PORT_PROTECTION_STATUS_ENABLED
}brsHw_Port_PortProtectionStatus;

typedef enum
{
  PORT_IP_CONTROL_DISABLED,
  PORT_IP_CONTROL_ENABLED
}brsHw_Port_PortIPControl;

typedef enum
{
  PORT_BIDIRECTIONAL_MODE_DISABLED,
  PORT_BIDIRECTIONAL_MODE_ENABLED
}brsHw_Port_BidirectionalMode;

typedef struct
{
  brsHw_Port_PortGroupType   portGroup;
  brsHw_Port_PortNumberType  portNumber;
  brsHw_Port_AlternativeType portAlternative;
}brsHw_Port_PortType;

typedef struct
{
  brsHw_Port_PullUpOption           PortPullUp;
  brsHw_Port_PortDriveStrength      PortDriveStrength;
  brsHw_Port_PortOpenDrainControl   PortOpenDrain;
  brsHw_Port_InputBufferSelect      PortInputBuffer;
  brsHw_Port_PortProtectionCommand  PortProtectionCMD;
  brsHw_Port_PortProtectionStatus   PortProtectionStatus;
  brsHw_Port_PortIPControl          PortIPControl;
  brsHw_Port_BidirectionalMode      PortBidirectionalMode;
}brsHw_Port_ConfType;

#if defined (_BRSHW_C_)
  #define BRSHW_PORT_PIN(name, group, number, alternative) const brsHw_Port_PortType name = {group, number, alternative}
#else
  #define BRSHW_PORT_PIN(name, group, number, alternative) extern const brsHw_Port_PortType name
#endif

#define BRSHW_PORT_LOGIC_HIGH (uint8)1
#define BRSHW_PORT_LOGIC_LOW  (uint8)0

/*******************************************************************************
 *  PIN configuration for alive LED support
 *******************************************************************************/
#if defined (BRS_ENABLE_SUPPORT_LEDS)
# if defined (BRS_EVA_BOARD_X1X_DEFAULT_EVB)
/* Supported by all controllers of the uC family */
BRSHW_PORT_PIN(BRSHW_PORT_LED, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_0);

# elif defined (BRS_EVA_BOARD_F1X_176PIN_EVB) || defined (BRS_EVA_BOARD_F1X_144PIN_EVB) || \
       defined (BRS_EVA_BOARD_F1X_064PIN_EVB) || defined (BRS_EVA_BOARD_F1X_100PIN_EVB)
/* LED 10, CN55.1, DIGIO_0 */
BRSHW_PORT_PIN(BRSHW_PORT_LED, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_0);

# elif defined (BRS_EVA_BOARD_P1XC_292PIN_EVB)
/*LED 10*/
BRSHW_PORT_PIN(BRSHW_PORT_LED, BRSHW_PORT_PORTGROUP_6, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_0);

# elif defined (BRS_EVA_BOARD_F1X_STARTERKIT_V2_EVB)
/*LED DBG_LED_GRN*/ /*LED 1*/
BRSHW_PORT_PIN(BRSHW_PORT_LED, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_11, BRSHW_PORT_ALT_0);

# elif defined (BRS_EVA_BOARD_P1X_144PIN_EVB)
BRSHW_PORT_PIN(BRSHW_PORT_LED, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_0);

# elif defined (BRS_EVA_BOARD_P1X_100PIN_EVB)
BRSHW_PORT_PIN(BRSHW_PORT_LED, BRSHW_PORT_PORTGROUP_2, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_0);

# elif defined (BRS_EVA_BOARD_P1XC_80PIN_EVB)
BRSHW_PORT_PIN(BRSHW_PORT_LED, BRSHW_PORT_PORTGROUP_2, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_0);

# else
  #error "Your chosen EvaBoard is not yet supported for LED support. Feel free to add your EvaBoard on top, or disable BRS LED support."
# endif /*BRS_EVA_BOARD_x*/
#endif /*BRS_ENABLE_SUPPORT_LEDS*/

/*******************************************************************************
 *  PIN configuration for toggle WD pin support
 *******************************************************************************/
#if defined (BRS_ENABLE_SUPPORT_TOGGLE_WD_PIN)
# if defined (BRS_ENABLE_FBL_SUPPORT)
  #define BRS_START_SEC_RAM_CONST
  #include "Brs_MemMap.h"
# endif

  #error "Please configure here the needed WD-toggle pin and uncomment this error, or disable BRS_ENABLE_SUPPORT_TOGGLE_WD_PIN"*/

BRSHW_PORT_PIN(BRSHW_PORT_TOGGLE_WD, BRSHW_PORT_PORTGROUP_x, BRSHW_PORT_PORTNUMBER_x, BRSHW_PORT_ALT_x);

# if defined (BRS_ENABLE_FBL_SUPPORT)
  #define BRS_STOP_SEC_RAM_CONST
  #include "Brs_MemMap.h"
# endif
#endif /*BRS_ENABLE_SUPPORT_WD_PIN*/

/*******************************************************************************
 *  PIN configuration for toggle CUSTOM pin support
 *******************************************************************************/
#if defined (BRS_ENABLE_SUPPORT_TOGGLE_CUSTOM_PIN)
# if defined (BRS_ENABLE_FBL_SUPPORT)
  #define BRS_START_SEC_RAM_CONST
  #include "Brs_MemMap.h"
# endif

  #error "Please configure here the needed custom toggle pin and uncomment this error, or disable BRS_ENABLE_SUPPORT_TOGGLE_CUSTOM_PIN"*/

BRSHW_PORT_PIN(BRSHW_PORT_TOGGLE_CUSTOM, BRSHW_PORT_PORTGROUP_x, BRSHW_PORT_PORTNUMBER_x, BRSHW_PORT_ALT_x);

# if defined (BRS_ENABLE_FBL_SUPPORT)
  #define BRS_STOP_SEC_RAM_CONST
  #include "Brs_MemMap.h"
# endif
#endif /*BRS_ENABLE_SUPPORT_CUSTOM_PIN*/

/*******************************************************************************
 *  ------------------------------------------------------------
 *  COMMUNICATION DRIVER SPECIFIC PORT SETTINGS
 *  ------------------------------------------------------------
 *******************************************************************************/
/*******************************************************************************
 *  GENERAL COMMUNICATION DRIVER SPECIFIC SETTINGS
 *******************************************************************************/
#if defined (_BRSHW_C_)

# if defined (BRS_ENABLE_LIN_SUPPORT)
const brsHw_Port_ConfType BRSHW_PORT_CONF_LIN = {
  PORT_PULL_UP_ENABLED,
  PORT_DRIVE_STRENGTH_CONTROL_DISABLED,
  PORT_OPEN_DRAIN_CONTROL_DISABLED,
  PORT_INPUT_BUFFER_CONTROL_DISABLED,
  PORT_PROTECTION_COMMAND_DISABLED,
  PORT_PROTECTION_STATUS_DISABLED,
  PORT_IP_CONTROL_DISABLED,
  PORT_BIDIRECTIONAL_MODE_DISABLED};
# endif /*BRS_ENABLE_LIN_SUPPORT*/

# if defined (BRS_ENABLE_ETHERNET_SUPPORT)
const brsHw_Port_ConfType BRSHW_PORT_CONF_ETH0_TXD = {
  PORT_PULL_UP_DISABLED,
  PORT_DRIVE_STRENGTH_CONTROL_ENABLED,
  PORT_OPEN_DRAIN_CONTROL_DISABLED,
  PORT_INPUT_BUFFER_CONTROL_DISABLED,
  PORT_PROTECTION_COMMAND_ENABLED,
  PORT_PROTECTION_STATUS_DISABLED,
  PORT_IP_CONTROL_DISABLED,
  PORT_BIDIRECTIONAL_MODE_DISABLED};
const brsHw_Port_ConfType BRSHW_PORT_CONF_ETH0_TXEN = {
  PORT_PULL_UP_DISABLED,
  PORT_DRIVE_STRENGTH_CONTROL_ENABLED,
  PORT_OPEN_DRAIN_CONTROL_DISABLED,
  PORT_INPUT_BUFFER_CONTROL_DISABLED,
  PORT_PROTECTION_COMMAND_ENABLED,
  PORT_PROTECTION_STATUS_DISABLED,
  PORT_IP_CONTROL_DISABLED,
  PORT_BIDIRECTIONAL_MODE_DISABLED};
const brsHw_Port_ConfType BRSHW_PORT_CONF_ETH0_TXER = {
  PORT_PULL_UP_DISABLED,
  PORT_DRIVE_STRENGTH_CONTROL_ENABLED,
  PORT_OPEN_DRAIN_CONTROL_DISABLED,
  PORT_INPUT_BUFFER_CONTROL_DISABLED,
  PORT_PROTECTION_COMMAND_ENABLED,
  PORT_PROTECTION_STATUS_DISABLED,
  PORT_IP_CONTROL_DISABLED,
  PORT_BIDIRECTIONAL_MODE_DISABLED};
const brsHw_Port_ConfType BRSHW_PORT_CONF_ETH0_MDC = {
  PORT_PULL_UP_DISABLED,
  PORT_DRIVE_STRENGTH_CONTROL_ENABLED,
  PORT_OPEN_DRAIN_CONTROL_DISABLED,
  PORT_INPUT_BUFFER_CONTROL_DISABLED,
  PORT_PROTECTION_COMMAND_ENABLED,
  PORT_PROTECTION_STATUS_DISABLED,
  PORT_IP_CONTROL_DISABLED,
  PORT_BIDIRECTIONAL_MODE_DISABLED};
const brsHw_Port_ConfType BRSHW_PORT_CONF_ETH0_MDIO = {
  PORT_PULL_UP_DISABLED,
  PORT_DRIVE_STRENGTH_CONTROL_ENABLED,
  PORT_OPEN_DRAIN_CONTROL_DISABLED,
  PORT_INPUT_BUFFER_CONTROL_DISABLED,
  PORT_PROTECTION_COMMAND_DISABLED,
  PORT_PROTECTION_STATUS_DISABLED,
  PORT_IP_CONTROL_ENABLED,
  PORT_BIDIRECTIONAL_MODE_DISABLED};
# endif /*BRS_ENABLE_ETHERNET_SUPPORT*/

#endif /* _BRSHW_C_ */

/*******************************************************************************
 *  CAN driver
 *******************************************************************************/
#if defined (BRS_ENABLE_CAN_SUPPORT)
# if defined (BRS_PORT_GROUP_A) || defined (BRS_PORT_GROUP_A1)
#define BRSHW_ENABLE_CAN_WAKEUP_FILTER
#  if defined (BRS_ENABLE_CAN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_TX, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_RX, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_2);
#  endif /*BRS_ENABLE_CAN_CHANNEL_0*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_2);
#  endif /*BRS_ENABLE_CAN_CHANNEL_1*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_2)
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_CAN_CHANNEL_2*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_3)
BRSHW_PORT_PIN(BRSHW_PORT_CAN3_TX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_CAN3_RX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_CAN_CHANNEL_3*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_4)
BRSHW_PORT_PIN(BRSHW_PORT_CAN4_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_10, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN4_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_9, BRSHW_PORT_ALT_5);
#  endif /*BRS_ENABLE_CAN_CHANNEL_4*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_5)
BRSHW_PORT_PIN(BRSHW_PORT_CAN5_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_14, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN5_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_13, BRSHW_PORT_ALT_5);
#  endif /*BRS_ENABLE_CAN_CHANNEL_5*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_6) || defined (BRS_ENABLE_CAN_CHANNEL_7) || \
      defined (BRS_ENABLE_CAN_CHANNEL_8) || defined (BRS_ENABLE_CAN_CHANNEL_9)
   #error "Port config for these CAN channels not yet implemented!"
#  endif

# elif defined (BRS_PORT_GROUP_B)
#define BRSHW_ENABLE_CAN_WAKEUP_FILTER
#  if defined (BRS_ENABLE_CAN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_TX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_3);
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_RX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_3);
#  endif /*BRS_ENABLE_CAN_CHANNEL_0*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_TX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_RX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_CAN_CHANNEL_1*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_2)
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_TX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_RX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_CAN_CHANNEL_2*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_3) || defined (BRS_ENABLE_CAN_CHANNEL_4) || \
      defined (BRS_ENABLE_CAN_CHANNEL_5) || defined (BRS_ENABLE_CAN_CHANNEL_6)
   #error "Port config for these CAN channels not yet implemented!"
#  endif

# elif defined (BRS_PORT_GROUP_B1)
#define BRSHW_ENABLE_CAN_WAKEUP_FILTER
#  if defined (BRS_ENABLE_CAN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_TX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_RX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_WAKEUP, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_7);
#  endif /*BRS_ENABLE_CAN_CHANNEL_0*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_TX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_15, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_RX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_14, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_WAKEUP, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_7);
#  endif /*BRS_ENABLE_CAN_CHANNEL_1*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_2)
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_WAKEUP, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_7);
#  endif /*BRS_ENABLE_CAN_CHANNEL_2*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_3)
BRSHW_PORT_PIN(BRSHW_PORT_CAN3_TX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN3_RX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN3_WAKEUP, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_7);
#  endif /*BRS_ENABLE_CAN_CHANNEL_3*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_4) || defined (BRS_ENABLE_CAN_CHANNEL_5) || \
      defined (BRS_ENABLE_CAN_CHANNEL_6) || defined (BRS_ENABLE_CAN_CHANNEL_7)
   #error "Port config for these CAN channels not yet implemented!"
#  endif

# elif defined (BRS_PORT_GROUP_B2)
#define BRSHW_ENABLE_CAN_WAKEUP_FILTER
#  if defined (BRS_ENABLE_CAN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_TX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_3);
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_RX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_3);
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_WAKEUP, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_12, BRSHW_PORT_ALT_2);
#  endif /*BRS_ENABLE_CAN_CHANNEL_0*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_14, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_13, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_WAKEUP, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_13, BRSHW_PORT_ALT_3);
#  endif /*BRS_ENABLE_CAN_CHANNEL_1*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_2)
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_TX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_11, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_RX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_10, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_WAKEUP, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_2);
#  endif /*BRS_ENABLE_CAN_CHANNEL_2*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_3)
BRSHW_PORT_PIN(BRSHW_PORT_CAN3_TX, BRSHW_PORT_PORTGROUP_9, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_CAN3_RX, BRSHW_PORT_PORTGROUP_9, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_CAN3_WAKEUP, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_2);
#  endif /*BRS_ENABLE_CAN_CHANNEL_3*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_4) || defined (BRS_ENABLE_CAN_CHANNEL_5) || \
      defined (BRS_ENABLE_CAN_CHANNEL_6) || defined (BRS_ENABLE_CAN_CHANNEL_7)
   #error "Port config for these CAN channels not yet implemented!"
#  endif

# elif defined (BRS_PORT_GROUP_C)
#define BRSHW_ENABLE_CAN_WAKEUP_FILTER
#  if defined (BRS_ENABLE_CAN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_4);
#  endif /*BRS_ENABLE_CAN_CHANNEL_0*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_4);
#  endif /*BRS_ENABLE_CAN_CHANNEL_1*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_2)
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_9, BRSHW_PORT_ALT_4);
#  endif /*BRS_ENABLE_CAN_CHANNEL_2*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_3) || defined (BRS_ENABLE_CAN_CHANNEL_4) || \
      defined (BRS_ENABLE_CAN_CHANNEL_5) || defined (BRS_ENABLE_CAN_CHANNEL_6)
   #error "Port config for these CAN channels not yet implemented!"
#  endif

# elif defined (BRS_PORT_GROUP_D)
#define BRSHW_ENABLE_CAN_WAKEUP_FILTER
#  if defined (BRS_ENABLE_CAN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_TX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_RX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_WAKEUP, BRSHW_PORT_PORTGROUP_2, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_7);
#  endif /*BRS_ENABLE_CAN_CHANNEL_0*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_TX, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_RX, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_WAKEUP, BRSHW_PORT_PORTGROUP_2, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_7);
#  endif /*BRS_ENABLE_CAN_CHANNEL_1*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_2)
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_TX, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_RX, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_WAKEUP, BRSHW_PORT_PORTGROUP_2, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_7);
#  endif /*BRS_ENABLE_CAN_CHANNEL_2*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_3)
BRSHW_PORT_PIN(BRSHW_PORT_CAN3_TX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_10, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN3_RX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_9, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN3_WAKEUP, BRSHW_PORT_PORTGROUP_2, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_7);
#  endif /*BRS_ENABLE_CAN_CHANNEL_3*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_4) || defined (BRS_ENABLE_CAN_CHANNEL_5) || \
      defined (BRS_ENABLE_CAN_CHANNEL_6) || defined (BRS_ENABLE_CAN_CHANNEL_7)
   #error "Port config for these CAN channels not yet implemented!"
#  endif

# elif defined (BRS_PORT_GROUP_E)
#define BRSHW_ENABLE_CAN_WAKEUP_FILTER
#  if defined (BRS_ENABLE_CAN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_TX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_RX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_WAKEUP, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_7);
#  endif /*BRS_ENABLE_CAN_CHANNEL_0*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_TX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_RX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_WAKEUP, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_7);
#  endif /*BRS_ENABLE_CAN_CHANNEL_1*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_2)
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN2_WAKEUP, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_7);
#  endif /*BRS_ENABLE_CAN_CHANNEL_2*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_3)
BRSHW_PORT_PIN(BRSHW_PORT_CAN3_TX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_15, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN3_RX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_14, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_CAN3_WAKEUP, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_7);
#  endif /*BRS_ENABLE_CAN_CHANNEL_3*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_4) || defined (BRS_ENABLE_CAN_CHANNEL_5) || \
      defined (BRS_ENABLE_CAN_CHANNEL_6) || defined (BRS_ENABLE_CAN_CHANNEL_7)
   #error "Port config for these CAN channels not yet implemented!"
#  endif

# elif defined (BRS_PORT_GROUP_F)
#define BRSHW_ENABLE_CAN_WAKEUP_FILTER
#  if defined (BRS_ENABLE_CAN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_TX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_3);
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_RX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_3);
BRSHW_PORT_PIN(BRSHW_PORT_CAN0_WAKEUP, BRSHW_PORT_PORTGROUP_2, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_2);
#  endif /*BRS_ENABLE_CAN_CHANNEL_0*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_TX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_3);
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_RX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_3);
BRSHW_PORT_PIN(BRSHW_PORT_CAN1_WAKEUP, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_3);
#  endif /*BRS_ENABLE_CAN_CHANNEL_1*/

#  if defined (BRS_ENABLE_CAN_CHANNEL_2) || defined (BRS_ENABLE_CAN_CHANNEL_3) || \
      defined (BRS_ENABLE_CAN_CHANNEL_4) || defined (BRS_ENABLE_CAN_CHANNEL_5)
   #error "Port config for these CAN channels not yet implemented!"
#  endif

# else
  #error "PortPins for your Port Group are not yet supported with CAN"
# endif /*BRS_PORT_GROUP_x*/
#endif /*BRS_ENABLE_CAN_SUPPORT*/

/*******************************************************************************
 *  LIN driver
 *******************************************************************************/
#if defined (BRS_ENABLE_LIN_SUPPORT)
# if defined (BRS_PORT_GROUP_A)
#  if defined (BRS_ENABLE_LIN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_LIN20_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_LIN20_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_2);
#  endif /*BRS_ENABLE_LIN_CHANNEL_0*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_LIN21_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN21_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_1*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_2)
BRSHW_PORT_PIN(BRSHW_PORT_LIN22_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_10, BRSHW_PORT_ALT_3);
BRSHW_PORT_PIN(BRSHW_PORT_LIN22_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_9, BRSHW_PORT_ALT_3);
#  endif /*BRS_ENABLE_LIN_CHANNEL_2*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_3)
BRSHW_PORT_PIN(BRSHW_PORT_LIN23_TX, BRSHW_PORT_PORTGROUP_20, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN23_RX, BRSHW_PORT_PORTGROUP_20, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_3*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_4)
BRSHW_PORT_PIN(BRSHW_PORT_LIN24_TX, BRSHW_PORT_PORTGROUP_11, BRSHW_PORT_PORTNUMBER_14, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN24_RX, BRSHW_PORT_PORTGROUP_11, BRSHW_PORT_PORTNUMBER_13, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_4*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_5)
BRSHW_PORT_PIN(BRSHW_PORT_LIN25_TX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN25_RX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_5*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_6)
BRSHW_PORT_PIN(BRSHW_PORT_LIN26_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_12, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_LIN26_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_11, BRSHW_PORT_ALT_4);
#  endif /*BRS_ENABLE_LIN_CHANNEL_6*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_7)
BRSHW_PORT_PIN(BRSHW_PORT_LIN27_TX, BRSHW_PORT_PORTGROUP_2, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN27_RX, BRSHW_PORT_PORTGROUP_2, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_0);
#  endif /*BRS_ENABLE_LIN_CHANNEL_7*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_8)
BRSHW_PORT_PIN(BRSHW_PORT_LIN28_TX, BRSHW_PORT_PORTGROUP_2, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN28_RX, BRSHW_PORT_PORTGROUP_2, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_8*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_9)
BRSHW_PORT_PIN(BRSHW_PORT_LIN29_TX, BRSHW_PORT_PORTGROUP_2, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN29_RX, BRSHW_PORT_PORTGROUP_2, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_9*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_10)
BRSHW_PORT_PIN(BRSHW_PORT_LIN30_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_LIN30_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_2);
#  endif /*BRS_ENABLE_LIN_CHANNEL_10*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_11)
BRSHW_PORT_PIN(BRSHW_PORT_LIN31_TX, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_12, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_LIN31_RX, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_11, BRSHW_PORT_ALT_2);
#  endif /*BRS_ENABLE_LIN_CHANNEL_11*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_12)
BRSHW_PORT_PIN(BRSHW_PORT_LIN32_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_14, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN32_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_13, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_12*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_13)
BRSHW_PORT_PIN(BRSHW_PORT_LIN33_TX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN33_RX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_13*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_14)
BRSHW_PORT_PIN(BRSHW_PORT_LIN34_TX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_9, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN34_RX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_14*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_15)
BRSHW_PORT_PIN(BRSHW_PORT_LIN35_TX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN35_RX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_15*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_16) || defined (BRS_ENABLE_LIN_CHANNEL_17)
   #error "Port config for these LIN channels not yet implemented!"
#  endif

# elif defined (BRS_PORT_GROUP_A1)
#  if defined (BRS_ENABLE_LIN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_LIN30_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_LIN30_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_2);
#  endif /*BRS_ENABLE_LIN_CHANNEL_0*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_LIN31_TX, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_12, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_LIN31_RX, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_11, BRSHW_PORT_ALT_2);
#  endif /*BRS_ENABLE_LIN_CHANNEL_1*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_2)
BRSHW_PORT_PIN(BRSHW_PORT_LIN32_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_14, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN32_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_13, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_2*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_3)
BRSHW_PORT_PIN(BRSHW_PORT_LIN33_TX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN33_RX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_3*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_4)
BRSHW_PORT_PIN(BRSHW_PORT_LIN34_TX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_9, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN34_RX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_4*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_5)
BRSHW_PORT_PIN(BRSHW_PORT_LIN35_TX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN35_RX, BRSHW_PORT_PORTGROUP_1, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_5*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_6) || defined (BRS_ENABLE_LIN_CHANNEL_7) || \
      defined (BRS_ENABLE_LIN_CHANNEL_8) || defined (BRS_ENABLE_LIN_CHANNEL_9)
   #error "Port config for these LIN channels not yet implemented!"
#  endif

# elif defined (BRS_PORT_GROUP_B)
#  if defined (BRS_ENABLE_LIN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_LIN30_TX, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_3);
BRSHW_PORT_PIN(BRSHW_PORT_LIN30_RX, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_3);
#  endif /*BRS_ENABLE_LIN_CHANNEL_0*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_LIN31_TX, BRSHW_PORT_PORTGROUP_2, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_3);
BRSHW_PORT_PIN(BRSHW_PORT_LIN31_RX, BRSHW_PORT_PORTGROUP_2, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_3);
#  endif /*BRS_ENABLE_LIN_CHANNEL_1*/

# elif defined (BRS_PORT_GROUP_B1)
#  if defined (BRS_ENABLE_LIN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_LIN20_TX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_LIN20_RX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_4);
#  endif /*BRS_ENABLE_LIN_CHANNEL_0*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_LIN21_TX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_LIN21_RX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_4);
#  endif /*BRS_ENABLE_LIN_CHANNEL_1*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_2)
BRSHW_PORT_PIN(BRSHW_PORT_LIN22_TX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_LIN22_RX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_4);
#  endif /*BRS_ENABLE_LIN_CHANNEL_2*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_3) || defined (BRS_ENABLE_LIN_CHANNEL_4) || \
      defined (BRS_ENABLE_LIN_CHANNEL_5) || defined (BRS_ENABLE_LIN_CHANNEL_6)
   #error "Port config for these LIN channels not yet implemented!"
#  endif

# elif defined (BRS_PORT_GROUP_B2)
#  if defined (BRS_ENABLE_LIN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_LIN30_TX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_LIN30_RX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_9, BRSHW_PORT_ALT_2);
#  endif /*BRS_ENABLE_LIN_CHANNEL_0*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_LIN31_TX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_LIN31_RX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_4);
#  endif /*BRS_ENABLE_LIN_CHANNEL_1*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_2)
BRSHW_PORT_PIN(BRSHW_PORT_LIN32_TX, BRSHW_PORT_PORTGROUP_7, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_LIN32_RX, BRSHW_PORT_PORTGROUP_7, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_4);
#  endif /*BRS_ENABLE_LIN_CHANNEL_2*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_3)
BRSHW_PORT_PIN(BRSHW_PORT_LIN33_TX, BRSHW_PORT_PORTGROUP_9, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_LIN33_RX, BRSHW_PORT_PORTGROUP_9, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_4);
#  endif /*BRS_ENABLE_LIN_CHANNEL_3*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_4) || defined (BRS_ENABLE_LIN_CHANNEL_5) || \
      defined (BRS_ENABLE_LIN_CHANNEL_6) || defined (BRS_ENABLE_LIN_CHANNEL_7)
   #error "Port config for these LIN channels not yet implemented!"
#  endif

# elif defined (BRS_PORT_GROUP_C)
#  if defined (BRS_ENABLE_LIN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_LIN30_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN30_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_9, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_0*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_LIN31_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN31_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_1*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_2)
BRSHW_PORT_PIN(BRSHW_PORT_LIN32_TX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_LIN32_RX, BRSHW_PORT_PORTGROUP_0, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_1);
#  endif /*BRS_ENABLE_LIN_CHANNEL_2*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_3) || defined (BRS_ENABLE_LIN_CHANNEL_4) || \
      defined (BRS_ENABLE_LIN_CHANNEL_5) || defined (BRS_ENABLE_LIN_CHANNEL_6)
   #error "Port config for these LIN channels not yet implemented!"
#  endif

# elif defined (BRS_PORT_GROUP_D)
#  if defined (BRS_ENABLE_LIN_CHANNEL_8)
BRSHW_PORT_PIN(BRSHW_PORT_LIN28_TX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_LIN28_RX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_4);
#  else
   #error "Port config is only implemented for LIN channel 8!"
#  endif /*BRS_ENABLE_LIN_CHANNEL_8*/

# elif defined (BRS_PORT_GROUP_E)
#  if defined (BRS_ENABLE_LIN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_LIN30_TX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_LIN30_RX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_4);
#  endif /*BRS_ENABLE_LIN_CHANNEL_0*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_LIN31_TX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_LIN31_RX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_4);
#  endif /*BRS_ENABLE_LIN_CHANNEL_1*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_2)
BRSHW_PORT_PIN(BRSHW_PORT_LIN32_TX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_LIN32_RX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_4);
#  endif /*BRS_ENABLE_LIN_CHANNEL_2*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_3) || defined (BRS_ENABLE_LIN_CHANNEL_4) || \
      defined (BRS_ENABLE_LIN_CHANNEL_5) || defined (BRS_ENABLE_LIN_CHANNEL_6)
   #error "Port config for these LIN channels not yet implemented!"
#  endif

# elif defined (BRS_PORT_GROUP_F)
#  if defined (BRS_ENABLE_LIN_CHANNEL_0)
BRSHW_PORT_PIN(BRSHW_PORT_LIN30_TX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_LIN30_RX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_9, BRSHW_PORT_ALT_2);
#  endif /*BRS_ENABLE_LIN_CHANNEL_0*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_1)
BRSHW_PORT_PIN(BRSHW_PORT_LIN31_TX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_LIN31_RX, BRSHW_PORT_PORTGROUP_5, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_4);
#  endif /*BRS_ENABLE_LIN_CHANNEL_1*/

#  if defined (BRS_ENABLE_LIN_CHANNEL_2) || defined (BRS_ENABLE_LIN_CHANNEL_3) || \
      defined (BRS_ENABLE_LIN_CHANNEL_4) || defined (BRS_ENABLE_LIN_CHANNEL_5)
   #error "Port config for these LIN channels not yet implemented!"
#  endif

# else
 #error "PortPins for your Port Group are not yet supported with LIN"
# endif /*BRS_PORT_GROUP_x*/
#endif /*BRS_ENABLE_LIN_SUPPORT*/

/*******************************************************************************
 *  FLEXRAY driver
 *******************************************************************************/
#if defined (BRS_ENABLE_FLEXRAY_SUPPORT)
# if defined (BRS_PORT_GROUP_A) || defined (BRS_PORT_GROUP_A1)
  /* ERAY-A */
BRSHW_PORT_PIN(BRSHW_PORT_FLX0A_TX, BRSHW_PORT_PORTGROUP_11, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_FLX0A_RX, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_14, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_FLX0A_TXEN, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_11, BRSHW_PORT_ALT_2);

  /* ERAY-B */
BRSHW_PORT_PIN(BRSHW_PORT_FLX0B_TX, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_FLX0B_RX, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_9, BRSHW_PORT_ALT_6);
BRSHW_PORT_PIN(BRSHW_PORT_FLX0B_TXEN, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_13, BRSHW_PORT_ALT_2);

# elif defined (BRS_PORT_GROUP_B)
  /* ERAY-A */
BRSHW_PORT_PIN(BRSHW_PORT_FLX0A_TX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_FLX0A_RX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_FLX0A_TXEN, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_5);

  /* ERAY-B */
BRSHW_PORT_PIN(BRSHW_PORT_FLX0B_TX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_FLX0B_RX, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_5);
BRSHW_PORT_PIN(BRSHW_PORT_FLX0B_TXEN, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_5);

# elif defined (BRS_PORT_GROUP_B2)
  /* ERAY-A */
BRSHW_PORT_PIN(BRSHW_PORT_FLX0A_TX, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_FLX0A_RX, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_FLX0A_TXEN, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_4);

  /* ERAY-B */
BRSHW_PORT_PIN(BRSHW_PORT_FLX0B_TX, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_FLX0B_RX, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_4);
BRSHW_PORT_PIN(BRSHW_PORT_FLX0B_TXEN, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_4);

/*FlexRay Modul 2 - NOT USED!*/
/*FLX1 Channel A:*/
/*const brsHw_Port_PortType BRSHW_PORT_FLX1_TX = {
  BRSHW_PORT_PORTGROUP_7,
  BRSHW_PORT_PORTNUMBER_5,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_FLX1_EN = {
  BRSHW_PORT_PORTGROUP_7,
  BRSHW_PORT_PORTNUMBER_6,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_FLX1_RX = {
  BRSHW_PORT_PORTGROUP_7,
  BRSHW_PORT_PORTNUMBER_7,
  BRSHW_PORT_ALT_2};*/
/*FLX1 Channel B:*/
/*const brsHw_Port_PortType BRSHW_PORT_FLX1_TX = {
  BRSHW_PORT_PORTGROUP_7,
  BRSHW_PORT_PORTNUMBER_3,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_FLX1_EN = {
  BRSHW_PORT_PORTGROUP_7,
  BRSHW_PORT_PORTNUMBER_1,
  BRSHW_PORT_ALT_2};
const brsHw_Port_PortType BRSHW_PORT_FLX1_RX = {
  BRSHW_PORT_PORTGROUP_7,
  BRSHW_PORT_PORTNUMBER_2,
  BRSHW_PORT_ALT_2};*/

# else
  #error "PortPins for your Port Group are not yet supported with FLX"
# endif /*BRS_PORT_GROUP_x*/
#endif /*BRS_ENABLE_FLEXRAY_SUPPORT*/

/*******************************************************************************
 *  ETHERNET driver
 *******************************************************************************/
#if defined (BRS_ENABLE_ETHERNET_SUPPORT)
# if defined (BRS_PORT_GROUP_A) || defined (BRS_PORT_GROUP_A1)
/* Management signals, used by every interface type */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_MDIO, BRSHW_PORT_PORTGROUP_12, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_4); /* MDIO */
#define _BRSHW_PORT_ETH0_MDC
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_MDC, BRSHW_PORT_PORTGROUP_12, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_2);  /* MDC */

/* Please select the Media-independent interface type, suitable for this board */
#define BRSHW_PORT_ETH0_TYPE_MII

#  if defined (BRSHW_PORT_ETH0_TYPE_MII)
/* Standard Media-independent interface */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXCLK, BRSHW_PORT_PORTGROUP_18, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_1); /* MII_TXCLK */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD0, BRSHW_PORT_PORTGROUP_18, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_2);  /* MII_TXD0 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD1, BRSHW_PORT_PORTGROUP_18, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_2);  /* MII_TXD1 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD2, BRSHW_PORT_PORTGROUP_18, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_2);  /* MII_TXD2 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD3, BRSHW_PORT_PORTGROUP_18, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_2);  /* MII_TXD3 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXEN, BRSHW_PORT_PORTGROUP_18, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_2);  /* MII_TXEN */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXER, BRSHW_PORT_PORTGROUP_18, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_1);  /* MII_TXER */

BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXCLK, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_6); /* MII_RXCLK */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD0, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_6);  /* MII_RXD0 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD1, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_6);  /* MII_RXD1 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD2, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_6);  /* MII_RXD2 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD3, BRSHW_PORT_PORTGROUP_10, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_6);  /* MII_RXD3 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXDV, BRSHW_PORT_PORTGROUP_11, BRSHW_PORT_PORTNUMBER_11, BRSHW_PORT_ALT_5); /* MII_RXDV */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXER, BRSHW_PORT_PORTGROUP_11, BRSHW_PORT_PORTNUMBER_14, BRSHW_PORT_ALT_5); /* MII_RXER */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_COL, BRSHW_PORT_PORTGROUP_11, BRSHW_PORT_PORTNUMBER_10, BRSHW_PORT_ALT_5);  /* MII_COL */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_CRS, BRSHW_PORT_PORTGROUP_11, BRSHW_PORT_PORTNUMBER_13, BRSHW_PORT_ALT_5);  /* MII_CRS */
#define _BRSHW_PORT_ETH0_RESET
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RESET, BRSHW_PORT_PORTGROUP_11, BRSHW_PORT_PORTNUMBER_9, BRSHW_PORT_ALT_0);  /* MII_RST */
#  endif /*BRSHW_PORT_ETH0_TYPE_MII*/

# elif defined (BRS_PORT_GROUP_B2)
/* Management signals, used by every interface type */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_MDIO, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_2); /* MDIO */
#define _BRSHW_PORT_ETH0_MDC
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_MDC, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_2);  /* MDC */

/* Please select the Media-independent interface type, suitable for this board */
#define BRSHW_PORT_ETH0_TYPE_MII

#  if defined (BRSHW_PORT_ETH0_TYPE_MII)
/* Standard Media-independent interface */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXCLK, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_2); /* MII_TXCLK */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD0, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_9, BRSHW_PORT_ALT_2);  /* MII_TXD0 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD1, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_10, BRSHW_PORT_ALT_2); /* MII_TXD1 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD2, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_12, BRSHW_PORT_ALT_2); /* MII_TXD2 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD3, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_13, BRSHW_PORT_ALT_2); /* MII_TXD3 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXEN, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_14, BRSHW_PORT_ALT_2); /* MII_TXEN */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXER, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_2);  /* MII_TXER */

BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXCLK, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_2); /* MII_RXCLK */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD0, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_2);  /* MII_RXD0 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD1, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_2);  /* MII_RXD1 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD2, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_2);  /* MII_RXD2 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD3, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_2);  /* MII_RXD3 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXDV, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_2);  /* MII_RXDV */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXER, BRSHW_PORT_PORTGROUP_4, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_2);  /* MII_RXER */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_COL, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_2);   /* MII_COL */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_CRS, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_2);   /* MII_CRS */
#define _BRSHW_PORT_ETH0_RESET
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RESET, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_2);  /* MII_RST */

/*Ethernet Modul 1*/
/*
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_TXCLK, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_TXD0, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_9, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_TXD1, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_11, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_TXD2, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_12, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_TXD3, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_13, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_TXEN, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_10, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_TXER, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_14, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_RXCLK, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_RXD0, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_RXD1, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_RXD2, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_RXD3, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_RXDV, BRSHW_PORT_PORTGROUP_7, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_3);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_RXER, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_COL, BRSHW_PORT_PORTGROUP_7, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_3);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_CRS, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_2);

const brsHw_Port_ConfType BRSHW_PORT_CONF_ETH1_MDIO = {
  PORT_PULL_UP_DISABLED,
  PORT_DRIVE_STRENGTH_CONTROL_DISABLED,
  PORT_OPEN_DRAIN_CONTROL_DISABLED,
  PORT_INPUT_BUFFER_CONTROL_DISABLED,
  PORT_PROTECTION_COMMAND_DISABLED,
  PORT_PROTECTION_STATUS_DISABLED,
  PORT_IP_CONTROL_DISABLED,
  PORT_BIDIRECTIONAL_MODE_ENABLED};

BRSHW_PORT_PIN(BRSHW_PORT_ETH1_MDIO, BRSHW_PORT_PORTGROUP_8, BRSHW_PORT_PORTNUMBER_15, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH1_MDC, BRSHW_PORT_PORTGROUP_7, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_3);
*/
#  endif /*BRSHW_PORT_ETH0_TYPE_MII*/

# elif defined (BRS_PORT_GROUP_C)
/* Management signals, used by every interface type */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_MDIO, BRSHW_PORT_PORTGROUP_3, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_2);  /* MDIO */

/* Please select the Media-independent interface type, suitable for this board */
#define BRSHW_PORT_ETH0_TYPE_MII

#  if defined (BRSHW_PORT_ETH0_TYPE_MII)
/* Standard Media-independent interface */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXCLK, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_1); /* MII_TXCLK */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD0, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_1);  /* MII_TXD0 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD1, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_1);  /* MII_TXD1 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD2, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_1);  /* MII_TXD2 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD3, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_1);  /* MII_TXD3 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXEN, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_1);  /* MII_TXEN */

/* Mango Board: Do not set these pins, otherwise the Eth piggy won't work correctly! */
/*
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXER, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_COL, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_CRS, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_1);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXER, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_15, BRSHW_PORT_ALT_1);*/

BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXCLK, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_9, BRSHW_PORT_ALT_1);  /* MII_RXCLK */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD0, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_13, BRSHW_PORT_ALT_1);  /* MII_RXD0 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD1, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_12, BRSHW_PORT_ALT_1);  /* MII_RXD1 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD2, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_11, BRSHW_PORT_ALT_1);  /* MII_RXD2 */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD3, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_10, BRSHW_PORT_ALT_1);  /* MII_RXD3 */

/*** ACHTUNG: Hier gibt es einen Fehler im Manual: "D1x_Mango_Main_Board_Manual_Rev0.05" *** */
/*** ATTENTION: Mistake in Manual: "D1x_Mango_Main_Board_Manual_Rev0.05" ******************* */
/*** ETHERNET_0 ETNB0RXDV_0 on P42_14 instead of P42_7 ************************************* */
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXDV, BRSHW_PORT_PORTGROUP_42, BRSHW_PORT_PORTNUMBER_14, BRSHW_PORT_ALT_1);  /* MII_RXDV */

/*Alternative Port Config for Ethernet Channel 0:  */
/*
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXCLK, BRSHW_PORT_PORTGROUP_46, BRSHW_PORT_PORTNUMBER_14, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD0, BRSHW_PORT_PORTGROUP_46, BRSHW_PORT_PORTNUMBER_9, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD1, BRSHW_PORT_PORTGROUP_46, BRSHW_PORT_PORTNUMBER_8, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD2, BRSHW_PORT_PORTGROUP_46, BRSHW_PORT_PORTNUMBER_7, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXD3, BRSHW_PORT_PORTGROUP_46, BRSHW_PORT_PORTNUMBER_6, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXEN, BRSHW_PORT_PORTGROUP_46, BRSHW_PORT_PORTNUMBER_10, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_TXER, BRSHW_PORT_PORTGROUP_46, BRSHW_PORT_PORTNUMBER_11, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXCLK, BRSHW_PORT_PORTGROUP_46, BRSHW_PORT_PORTNUMBER_15, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD0, BRSHW_PORT_PORTGROUP_47, BRSHW_PORT_PORTNUMBER_3, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD1, BRSHW_PORT_PORTGROUP_47, BRSHW_PORT_PORTNUMBER_2, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD2, BRSHW_PORT_PORTGROUP_47, BRSHW_PORT_PORTNUMBER_1, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXD3, BRSHW_PORT_PORTGROUP_47, BRSHW_PORT_PORTNUMBER_0, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXDV, BRSHW_PORT_PORTGROUP_47, BRSHW_PORT_PORTNUMBER_4, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_RXER, BRSHW_PORT_PORTGROUP_47, BRSHW_PORT_PORTNUMBER_5, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_COL, BRSHW_PORT_PORTGROUP_46, BRSHW_PORT_PORTNUMBER_12, BRSHW_PORT_ALT_2);
BRSHW_PORT_PIN(BRSHW_PORT_ETH0_CRS, BRSHW_PORT_PORTGROUP_46, BRSHW_PORT_PORTNUMBER_13, BRSHW_PORT_ALT_2);
*/
#  endif /*BRSHW_PORT_ETH0_TYPE_MII*/

# else
  #error "PortPins for your Port Group are not yet supported with ETH"
# endif /*BRS_PORT_GROUP_x*/
#endif /*BRS_ENABLE_ETHERNET_SUPPORT*/

#endif /*_BRSHW_PORTS_H_*/
